language: node_js
node_js:
- 6
script:
- npm run coverage
after_success:
- npm install coveralls
- cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
before_install:
- openssl aes-256-cbc -K $encrypted_d458e99742b2_key -iv $encrypted_d458e99742b2_iv
  -in test/fixtures/s3-config.json.enc -out test/fixtures/s3-config.json -d
